### ISSUE TITLE
The 3 seems to have an extra component

### ISSUE THREAD

**Issue by rimas-kudelis** [gheja/wu3-segments#4]
I suspect this might be intentional, but the 3 glyph in your screenshots has an extra component on, which is not seen in your original photos:

![image](https://github.com/user-attachments/assets/ba167ed4-112e-4001-968d-3c9db4a4b216)

EDIT: also, the little corners appear to be missing:
![image](https://github.com/user-attachments/assets/4fe388b4-1ece-4fd1-89c0-36cae80ead06)

**Comment by gheja** [comment]
Oh, you're right! I will fix these sometime, thanks!

**Comment by gheja** [comment]
Thanks for pointing this out, I fixed it in v0.13.
