### ISSUE TITLE
Move comma one segment down

### ISSUE THREAD

**Issue by rimas-kudelis** [gheja/wu3-segments#5]
It looks like the comma could go down by one segment, and still retain its shape almost unaffected. I think this would make more sense than making it stick above the full stop character, wouldn't you agree?

**Comment by gheja** [comment]
That would work, probably, I will check.

**Comment by gheja** [comment]
I have checked the [source](https://futurezone.at/digital-life/wiener-linien-crashen-echtzeitanzeige-mit-klima-schuetzen/400507669) where I found the `,` character and the one in the font matches. Although it would indeed work a segment lower and might be even more in line with the `.`, the current one is identical to the original, so I will keep it this way. But thanks for taking the time to think about it and share this with me!

![image](https://github.com/user-attachments/assets/497c222a-4b06-49b3-bbfb-04be796f14de)
